// Question 389. FInd the difference
// You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.



class Solution {
    public char findTheDifference(String s, String t) {
        char[] arr1 = s.toCharArray();
        char[] arr2 = t.toCharArray();
        Arrays.sort(arr1);
        Arrays.sort(arr2);
        // Iterate through the sorted arrays and compare characters
        for(int i=0; i< arr1.length; i++){
            // If a character from 't' is not equal to the corresponding character from 's', return that character
            if(arr1[i] != arr2[i]){
                return (arr2[i]);
            }

        } 
        // If no difference is found, return the last character of 't', which is the extra character
        return (arr2[arr2.length - 1]);
    }
}
